### ISSUE TITLE
Correct GPU not being detected

### ISSUE THREAD

**Issue by shidib09** [iulicc/NZXT-Starfield-compass-Web-Integration#1]
Hello,

First I wanted to say your custom web integration is AWESOME. I love it. But I am having an issue with the GPU temp displaying my integrated gpu temp and not my actual GPUs temp.  So i took a look at your code and I believe the issue is here. 

https://github.com/iulicc/NZXT-Starfield-compass-Web-Integration/blob/main/public/js/main.js#L24

Since it sees my integrated gpu first and the index is set ot 0, I believe it is defaulting to that no matter what I select in NZXT CAMs interface. I could be wrong but just wanted to see your thoughts. 

![GPU nzxt cam](https://github.com/iulicc/NZXT-Starfield-compass-Web-Integration/assets/34924523/e7c4a1e2-d5a6-43f0-ba9c-ad467e7b6c22)

**Comment by iulicc** [comment]
Hey there! 👋 It seems like your integrated GPU keeps showing up with an index of 0, no matter what you pick in NZXT CAM.

So, I've made a little tweak in commit ef0c1b5! Now, if your device has more than one GPU (just like yours does), it should display the temperature for the second one at index 1. This is just a temporary solution as it only covers the scenario where the GPU at index 0 is an integrated one. I will need to come up with a better solution, maybe display the temperature of all available GPUs.

I haven't got multiple GPUs myself, so I couldn't test it out. Could you give it a whirl and let me know if it's showing the right temp on your end now? Appreciate your help! 😊

**Comment by shidib09** [comment]
Yup looks good now! I did also test it locally myself with just moving the index to 1 but would prefer if I could just use the web url over running it locally of course :) thank you again for the quick response!
